:

set -u

NETWOXDEF_VERSIONMAJOR=5
export NETWOXDEF_VERSIONMAJOR

NETWOXDEF_VERSIONMINOR=39
export NETWOXDEF_VERSIONMINOR

NETWOXDEF_VERSIONMICRO=0
export NETWOXDEF_VERSIONMICRO

NETWOXDEF_VERSION="$NETWOXDEF_VERSIONMAJOR.$NETWOXDEF_VERSIONMINOR.$NETWOXDEF_VERSIONMICRO"

#NETWOXDEF_VERSION=$NETWOXDEF_VERSION".pre1"

export NETWOXDEF_VERSION


