
/*-------------------------------------------------------------*/
typedef enum {
  NETWOX_SERVICES_FTP = 21,
  NETWOX_SERVICES_TELNET = 23,
  NETWOX_SERVICES_SMTP = 25,
  NETWOX_SERVICES_WHOIS = 43,
  NETWOX_SERVICES_DOMAIN = 53,
  NETWOX_SERVICES_DNS = NETWOX_SERVICES_DOMAIN,
  NETWOX_SERVICES_TFTP = 69,
  NETWOX_SERVICES_DHCP4S = 67, /* server */
  NETWOX_SERVICES_DHCP4C = 68, /* client */
  NETWOX_SERVICES_WWW = 80,
  NETWOX_SERVICES_HTTP = NETWOX_SERVICES_WWW,
  NETWOX_SERVICES_IDENT = 113,
  NETWOX_SERVICES_NNTP = 119,
  NETWOX_SERVICES_NTP = 123,
  NETWOX_SERVICES_SMBNBTSS = 139,
  NETWOX_SERVICES_SNMP = 161,
  NETWOX_SERVICES_SNMPTRAP = 162,
  NETWOX_SERVICES_HTTPS = 443,
  NETWOX_SERVICES_SMBNAKED = 445,
  NETWOX_SERVICES_SYSLOG = 514
} netwox_services;
