:

set -u

NETWIBDEF_VERSIONMAJOR=5
export NETWIBDEF_VERSIONMAJOR

NETWIBDEF_VERSIONMINOR=39
export NETWIBDEF_VERSIONMINOR

NETWIBDEF_VERSIONMICRO=0
export NETWIBDEF_VERSIONMICRO

NETWIBDEF_VERSION="$NETWIBDEF_VERSIONMAJOR.$NETWIBDEF_VERSIONMINOR.$NETWIBDEF_VERSIONMICRO"

#NETWIBDEF_VERSION=$NETWIBDEF_VERSION".pre1"

export NETWIBDEF_VERSION
