:

set -u

NETWAGDEF_VERSIONMAJOR=5
export NETWAGDEF_VERSIONMAJOR

NETWAGDEF_VERSIONMINOR=39
export NETWAGDEF_VERSIONMINOR

NETWAGDEF_VERSIONMICRO=0
export NETWAGDEF_VERSIONMICRO

NETWAGDEF_VERSION="$NETWAGDEF_VERSIONMAJOR.$NETWAGDEF_VERSIONMINOR.$NETWAGDEF_VERSIONMICRO"

#NETWAGDEF_VERSION=$NETWAGDEF_VERSION".pre1"

export NETWAGDEF_VERSION

