.TH NETWAG 1 "08/07/2012"
.SH NAME
\fBnetwag\fR - graphical front end for netwox

.SH VERSION
The version installed on this system is 5.39.0.

.SH IMPORTANT
Manpage do not contain a lot of information. Rather read
netwag-5.39.0-doc_html.tgz.

.SH SYNOPSIS
.B netwag
.br

.SH DESCRIPTION
.PP
Netwag is a graphical front end for netwox.

.SH SEE ALSO
.IR netwox (1)
.IR netwib (3)
