.TH NETWIB_ERR 3 "08/07/2012"
.SH NAME
\fBnetwib\fR - section \fBerr\fR

.SH HTML DOC
If you have a browser, read netwib-5.39.0-doc_html.tgz
which is easier to read than this manpage.

.SH PRESENTATION
This manpage contains a concatenation of includes for section
ERR.
.SH ERROR CODES
.nf

/*
Error ranges :
  0          : OK
  1000..1999 : frequent errors
  2000..2999 : parameter errors
  3000..3999 : logical errors
  4000..9999 : function errors
  10000..end : user errors codes
*/
\fI#define\fP \fBNETWIB_ERRZONE_USER_BEGIN\fP 10000

\fItypedef\fP enum {
  /* no error */
  \fBNETWIB_ERR_OK\fP = 0,
  /* frequent errors */
  \fBNETWIB_ERR_DATAEND\fP = 1000,
  \fBNETWIB_ERR_DATANOTAVAIL\fP,
  \fBNETWIB_ERR_DATANOSPACE\fP,
  \fBNETWIB_ERR_DATAOTHERTYPE\fP,
  \fBNETWIB_ERR_DATAMISSING\fP,
  \fBNETWIB_ERR_NOTFOUND\fP,
  \fBNETWIB_ERR_NOTCONVERTED\fP,
  \fBNETWIB_ERR_ROUTELOCALDEV\fP,
  \fBNETWIB_ERR_ROUTENOTFOUND\fP,
  \fBNETWIB_ERR_ROUTENOTETHER\fP,
  \fBNETWIB_ERR_PLEASETRYNEXT\fP,
  \fBNETWIB_ERR_PLEASECONSTRUCT\fP,
  \fBNETWIB_ERR_PLEASELOOPTIME\fP,
  /* parameter errors */
  \fBNETWIB_ERR_PAINVALIDTYPE\fP = 2000,
  \fBNETWIB_ERR_PAINVALIDPOS\fP,
  \fBNETWIB_ERR_PAINVALIDRANGE\fP,
  \fBNETWIB_ERR_PAINVALIDDEFAULT\fP,
  \fBNETWIB_ERR_PANULLPTR\fP,
  \fBNETWIB_ERR_PANULLPTRSIZE\fP,
  \fBNETWIB_ERR_PATOOLOW\fP,
  \fBNETWIB_ERR_PATOOHIGH\fP,
  \fBNETWIB_ERR_PAHEXACHAR\fP,
  \fBNETWIB_ERR_PAHEXAODD\fP,
  \fBNETWIB_ERR_PAMIXED\fP,
  \fBNETWIB_ERR_PABASE64CHAR\fP,
  \fBNETWIB_ERR_PABASE64X4\fP,
  \fBNETWIB_ERR_PABASE64LO\fP,
  \fBNETWIB_ERR_PAFMT\fP,
  \fBNETWIB_ERR_PAINT\fP,
  \fBNETWIB_ERR_PARINGFULL\fP,
  \fBNETWIB_ERR_PATLVINVALID\fP,
  \fBNETWIB_ERR_PATIMEDIFFNEG\fP,
  \fBNETWIB_ERR_PAPATHROOTDOTDOT\fP,
  \fBNETWIB_ERR_PAPATHNOTCANON\fP,
  \fBNETWIB_ERR_PAPATHCANTINIT\fP,
  \fBNETWIB_ERR_PAFILE2G\fP,
  \fBNETWIB_ERR_PAFILENOTREG\fP,
  \fBNETWIB_ERR_PAINDEXNODATA\fP,
  \fBNETWIB_ERR_PATOOBIGFORHDR\fP,
  \fBNETWIB_ERR_PAIP4OPTSNOTX4\fP,
  \fBNETWIB_ERR_PAIP4OPTSMAX10\fP,
  \fBNETWIB_ERR_PAIP6EXTSNOTX4\fP,
  \fBNETWIB_ERR_PATCPOPTSNOTX4\fP,
  \fBNETWIB_ERR_PATCPOPTSMAX10\fP,
  \fBNETWIB_ERR_PAIPTYPE\fP,
  \fBNETWIB_ERR_PAIPTYPENOT4\fP,
  \fBNETWIB_ERR_PAIPTYPENOT6\fP,
  /* logical errors */
  \fBNETWIB_ERR_LOINTERNALERROR\fP = 3000,
  \fBNETWIB_ERR_LONOTIMPLEMENTED\fP,
  \fBNETWIB_ERR_LONOTSUPPORTED\fP,
  \fBNETWIB_ERR_LOERROROKKO\fP,
  \fBNETWIB_ERR_LOOBJINITALREADYINIT\fP,
  \fBNETWIB_ERR_LOOBJUSENOTINITIALIZED\fP,
  \fBNETWIB_ERR_LOOBJUSECLOSED\fP,
  \fBNETWIB_ERR_LOOBJUSECORRUPT\fP,
  \fBNETWIB_ERR_LOOBJCLOSENOTINITIALIZED\fP,
  \fBNETWIB_ERR_LOOBJCLOSEALREADYCLOSED\fP,
  \fBNETWIB_ERR_LOOBJCLOSECORRUPT\fP,
  \fBNETWIB_ERR_LOOBJREADNOTSUPPORTED\fP,
  \fBNETWIB_ERR_LOOBJREADNOTALLOWED\fP,
  \fBNETWIB_ERR_LOOBJWRITENOTSUPPORTED\fP,
  \fBNETWIB_ERR_LOOBJWRITENOTALLOWED\fP,
  \fBNETWIB_ERR_LOOBJRDWRCONFLICT\fP,
  \fBNETWIB_ERR_LOCANTEXEC\fP,
  \fBNETWIB_ERR_LOUDPSERREADBEFWRITE\fP,
  /* system functions errors */
  \fBNETWIB_ERR_FUACCEPT\fP = 4000,
  \fBNETWIB_ERR_FUBIND\fP,
  \fBNETWIB_ERR_FUCHDIR\fP,
  \fBNETWIB_ERR_FUCHMOD\fP,
  \fBNETWIB_ERR_FUCHOWN\fP,
  \fBNETWIB_ERR_FUCLOCKGETTIME\fP,
  \fBNETWIB_ERR_FUCLOSE\fP,
  \fBNETWIB_ERR_FUCLOSEDIR\fP,
  \fBNETWIB_ERR_FUCLOSEHANDLE\fP,
  \fBNETWIB_ERR_FUCONNECT\fP,
  \fBNETWIB_ERR_FUCREATEEVENT\fP,
  \fBNETWIB_ERR_FUCREATEFILE\fP,
  \fBNETWIB_ERR_FUCREATEMUTEX\fP,
  \fBNETWIB_ERR_FUCREATEPIPE\fP,
  \fBNETWIB_ERR_FUCREATETHREAD\fP,
  \fBNETWIB_ERR_FUDUP2\fP,
  \fBNETWIB_ERR_FUDUPLICATEHANDLE\fP,
  \fBNETWIB_ERR_FUEXECLE\fP,
  \fBNETWIB_ERR_FUFCLOSE\fP,
  \fBNETWIB_ERR_FUFCNTL\fP,
  \fBNETWIB_ERR_FUFFLUSH\fP,
  \fBNETWIB_ERR_FUFILENO\fP,
  \fBNETWIB_ERR_FUFINDCLOSE\fP,
  \fBNETWIB_ERR_FUFOPEN\fP,
  \fBNETWIB_ERR_FUFORK\fP,
  \fBNETWIB_ERR_FUFREAD\fP,
  \fBNETWIB_ERR_FUFREELIBRARY\fP,
  \fBNETWIB_ERR_FUFSYNC\fP,
  \fBNETWIB_ERR_FUFTRUNCATE\fP,
  \fBNETWIB_ERR_FUFWRITE\fP,
  \fBNETWIB_ERR_FUGENERATECONSOLECTRLEVENT\fP,
  \fBNETWIB_ERR_FUGETCONSOLEMODE\fP,
  \fBNETWIB_ERR_FUGETEXITCODEPROCESS\fP,
  \fBNETWIB_ERR_FUGETEXITCODETHREAD\fP,
  \fBNETWIB_ERR_FUGETGRGIDR\fP,
  \fBNETWIB_ERR_FUGETGRNAMR\fP,
  \fBNETWIB_ERR_FUGETIFTABLE\fP,
  \fBNETWIB_ERR_FUGETIPADDRTABLE\fP,
  \fBNETWIB_ERR_FUGETIPFORWARDTABLE\fP,
  \fBNETWIB_ERR_FUGETIPNETTABLE\fP,
  \fBNETWIB_ERR_FUGETMSG\fP,
  \fBNETWIB_ERR_FUGETPEERNAME\fP,
  \fBNETWIB_ERR_FUGETPROCADDRESS\fP,
  \fBNETWIB_ERR_FUGETPWNAMR\fP,
  \fBNETWIB_ERR_FUGETPWUID\fP,
  \fBNETWIB_ERR_FUGETRLIMIT\fP,
  \fBNETWIB_ERR_FUGETSOCKNAME\fP,
  \fBNETWIB_ERR_FUGETTIMEOFDAY\fP,
  \fBNETWIB_ERR_FUGETUID\fP,
  \fBNETWIB_ERR_FUGLOBALALLOC\fP,
  \fBNETWIB_ERR_FUGLOBALFREE\fP,
  \fBNETWIB_ERR_FULOCALTIMER\fP,
  \fBNETWIB_ERR_FUIOCTL\fP,
  \fBNETWIB_ERR_FUKILL\fP,
  \fBNETWIB_ERR_FULIBNETCLOSELINKINT\fP,
  \fBNETWIB_ERR_FULIBNETCLOSERAWSOCK\fP,
  \fBNETWIB_ERR_FULIBNETINIT\fP,
  \fBNETWIB_ERR_FULIBNETOPENRAWSOCK\fP,
  \fBNETWIB_ERR_FULIBNETWRITEIP\fP,
  \fBNETWIB_ERR_FULIBNETWRITELINK\fP,
  \fBNETWIB_ERR_FULIBNETWRITELL\fP,
  \fBNETWIB_ERR_FULIBNETWRITERAWIPV4\fP,
  \fBNETWIB_ERR_FULIBNETWRITERAWIPV6\fP,
  \fBNETWIB_ERR_FULISTEN\fP,
  \fBNETWIB_ERR_FULOADLIBRARY\fP,
  \fBNETWIB_ERR_FULSEEK\fP,
  \fBNETWIB_ERR_FULSTAT\fP,
  \fBNETWIB_ERR_FUMALLOC\fP,
  \fBNETWIB_ERR_FUMKDIR\fP,
  \fBNETWIB_ERR_FUMPROTECT\fP,
  \fBNETWIB_ERR_FUNANOSLEEP\fP,
  \fBNETWIB_ERR_FUOPEN\fP,
  \fBNETWIB_ERR_FUOPENDIR\fP,
  \fBNETWIB_ERR_FUOPENPROCESS\fP,
  \fBNETWIB_ERR_FUOPENPTY\fP,
  \fBNETWIB_ERR_FUPACKETALLOCATEPACKET\fP,
  \fBNETWIB_ERR_FUPACKETGETNETTYPE\fP,
  \fBNETWIB_ERR_FUPACKETOPENADAPTER\fP,
  \fBNETWIB_ERR_FUPACKETREQUEST\fP,
  \fBNETWIB_ERR_FUPACKETSENDPACKET\fP,
  \fBNETWIB_ERR_FUPACKETSETBUFF\fP,
  \fBNETWIB_ERR_FUPCAPCOMPILE\fP,
  \fBNETWIB_ERR_FUPCAPDUMPOPEN\fP,
  \fBNETWIB_ERR_FUPCAPFINDALLDEVS\fP,
  \fBNETWIB_ERR_FUPCAPGETEVENT\fP,
  \fBNETWIB_ERR_FUPCAPOPENDEAD\fP,
  \fBNETWIB_ERR_FUPCAPOPENOFFLINE\fP,
  \fBNETWIB_ERR_FUPCAPSETFILTER\fP,
  \fBNETWIB_ERR_FUPEEKCONSOLEINPUT\fP,
  \fBNETWIB_ERR_FUPIPE\fP,
  \fBNETWIB_ERR_FUPOLL\fP,
  \fBNETWIB_ERR_FUPTHREADATTRINIT\fP,
  \fBNETWIB_ERR_FUPTHREADATTRDESTROY\fP,
  \fBNETWIB_ERR_FUPTHREADATTRSETDETACHSTATE\fP,
  \fBNETWIB_ERR_FUPTHREADCONDINIT\fP,
  \fBNETWIB_ERR_FUPTHREADCONDBROADCAST\fP,
  \fBNETWIB_ERR_FUPTHREADCONDDESTROY\fP,
  \fBNETWIB_ERR_FUPTHREADCONDTIMEDWAIT\fP,
  \fBNETWIB_ERR_FUPTHREADCONDWAIT\fP,
  \fBNETWIB_ERR_FUPTHREADCREATE\fP,
  \fBNETWIB_ERR_FUPTHREADDELAYNP\fP,
  \fBNETWIB_ERR_FUPTHREADGETEXPIRATIONNP\fP,
  \fBNETWIB_ERR_FUPTHREADGETSPECIFIC\fP,
  \fBNETWIB_ERR_FUPTHREADJOIN\fP,
  \fBNETWIB_ERR_FUPTHREADKEYCREATE\fP,
  \fBNETWIB_ERR_FUPTHREADKEYDELETE\fP,
  \fBNETWIB_ERR_FUPTHREADMUTEXINIT\fP,
  \fBNETWIB_ERR_FUPTHREADMUTEXDESTROY\fP,
  \fBNETWIB_ERR_FUPTHREADMUTEXLOCK\fP,
  \fBNETWIB_ERR_FUPTHREADMUTEXTIMEDLOCK\fP,
  \fBNETWIB_ERR_FUPTHREADMUTEXTRYLOCK\fP,
  \fBNETWIB_ERR_FUPTHREADMUTEXUNLOCK\fP,
  \fBNETWIB_ERR_FUPTHREADRWLOCKINIT\fP,
  \fBNETWIB_ERR_FUPTHREADRWLOCKDESTROY\fP,
  \fBNETWIB_ERR_FUPTHREADRWLOCKRDLOCK\fP,
  \fBNETWIB_ERR_FUPTHREADRWLOCKWRLOCK\fP,
  \fBNETWIB_ERR_FUPTHREADRWLOCKTIMEDRDLOCK\fP,
  \fBNETWIB_ERR_FUPTHREADRWLOCKTIMEDWRLOCK\fP,
  \fBNETWIB_ERR_FUPTHREADRWLOCKTRYRDLOCK\fP,
  \fBNETWIB_ERR_FUPTHREADRWLOCKTRYWRLOCK\fP,
  \fBNETWIB_ERR_FUPTHREADRWLOCKUNLOCK\fP,
  \fBNETWIB_ERR_FUPTHREADSETSPECIFIC\fP,
  \fBNETWIB_ERR_FUPUTMSG\fP,
  \fBNETWIB_ERR_FUREAD\fP,
  \fBNETWIB_ERR_FUREADDIRR\fP,
  \fBNETWIB_ERR_FUREADLINK\fP,
  \fBNETWIB_ERR_FUREALLOC\fP,
  \fBNETWIB_ERR_FURECV\fP,
  \fBNETWIB_ERR_FURECVFROM\fP,
  \fBNETWIB_ERR_FUREGCLOSEKEY\fP,
  \fBNETWIB_ERR_FUREGCOMP\fP,
  \fBNETWIB_ERR_FUREGENUMKEY\fP,
  \fBNETWIB_ERR_FUREGENUMVALUE\fP,
  \fBNETWIB_ERR_FUREGOPENKEYEX\fP,
  \fBNETWIB_ERR_FUREGQUERYINFOKEY\fP,
  \fBNETWIB_ERR_FUREGQUERYVALUEEX\fP,
  \fBNETWIB_ERR_FURELEASEMUTEX\fP,
  \fBNETWIB_ERR_FURENAME\fP,
  \fBNETWIB_ERR_FURESETEVENT\fP,
  \fBNETWIB_ERR_FURMDIR\fP,
  \fBNETWIB_ERR_FUSELECT\fP,
  \fBNETWIB_ERR_FUSEND\fP,
  \fBNETWIB_ERR_FUSENDTO\fP,
  \fBNETWIB_ERR_FUSETEVENT\fP,
  \fBNETWIB_ERR_FUSETGID\fP,
  \fBNETWIB_ERR_FUSETGROUPS\fP,
  \fBNETWIB_ERR_FUSETSID\fP,
  \fBNETWIB_ERR_FUSETUID\fP,
  \fBNETWIB_ERR_FUSETSOCKOPT\fP,
  \fBNETWIB_ERR_FUSIGNAL\fP,
  \fBNETWIB_ERR_FUSNMPEXTENSIONINIT\fP,
  \fBNETWIB_ERR_FUSNMPEXTENSIONQUERY\fP,
  \fBNETWIB_ERR_FUSOCKET\fP,
  \fBNETWIB_ERR_FUSYMLINK\fP,
  \fBNETWIB_ERR_FUSYSCTL\fP,
  \fBNETWIB_ERR_FUTCGETATTR\fP,
  \fBNETWIB_ERR_FUTCSETATTR\fP,
  \fBNETWIB_ERR_FUTERMINATEPROCESS\fP,
  \fBNETWIB_ERR_FUTLSALLOC\fP,
  \fBNETWIB_ERR_FUTLSFREE\fP,
  \fBNETWIB_ERR_FUTLSSETVALUE\fP,
  \fBNETWIB_ERR_FUUNLINK\fP,
  \fBNETWIB_ERR_FUVIRTUALALLOC\fP,
  \fBNETWIB_ERR_FUVIRTUALFREE\fP,
  \fBNETWIB_ERR_FUVIRTUALPROTECT\fP,
  \fBNETWIB_ERR_FUWAITFORSINGLEOBJECT\fP,
  \fBNETWIB_ERR_FUWAITPID\fP,
  \fBNETWIB_ERR_FUWRITE\fP,
  \fBNETWIB_ERR_FUWRITEFILE\fP,
  \fBNETWIB_ERR_FUWSACLEANUP\fP,
  \fBNETWIB_ERR_FUWSASTARTUP\fP
} \fBnetwib_err\fP;
.fi
.SH SEE ALSO
.IR netwib (3),
.IR netwib_dat (3),
.IR netwib_sys (3),
.IR netwib_net (3),
.IR netwib_pkt (3),
.IR netwib_shw (3),
.IR netwib_err (3)
